#!/usr/bin/python3
from curses import COLOR_WHITE
import sys
import threading
from turtle import color
from pinger import connect, send_nick, notif
from tkinter import Tk, Label, Text, Button, PhotoImage, END, mainloop

connected = 0
client = None
nickname = ""

# tkinter setup
root = Tk()
root.geometry("220x150")
root.title("Pinger! ")
root['bg'] = '#26242f'
root.iconphoto(False, PhotoImage(file='bell.png'))


def pinger():
    # A function for receive data from server
    # you found more comment in pinger.py
    while True:
        try:
            message = client.recv(16).decode('utf8')
            if message[:5] == "PING ":
                Output.config(text=message)
                notif(message)
            elif message[:6] == "PINGED":
                Output.config(text=message)
            elif message == "Why?":
                Output.config(text=message)
            elif message == "404":
                Output.config(text=message)
            else:
                print("unknown message: ", message)
                client.close()
                print("connection close")
                sys.exit(1)
        except:
            print("An error occured!")
            client.close()
            sys.exit(1)


def Take_input():
    # A function for take input such as nickname
    global client, connected, nickname
    # Get input
    INPUT = inputtxt.get("1.0", "end-1c").strip()
    # Check input not empty
    if INPUT == '':
        return 0
    # this segment is executed if app not connect to server
    if not connected:
        nickname = INPUT
        client = connect(nickname)
        Output.config(text=f"Connect with {nickname}")
        root.title(f"Pinger! ({nickname})")
        l.config(text="Nick for Ping:")
        Button0.config(text="Ping!")
        # Start ping receiver
        receive_thread.start()
        connected = 1
    # this segment is executed if app connected to server
    else:
        send_nick(INPUT)
    # flush textbox
    inputtxt.delete('1.0', END)


l = Label(text="Your nickname?",
          font=('Times New Roman', 15, 'bold'),
          fg="white",
          bg="#26242f")

inputtxt = Text(root, height=1,
                width=15,
                font=('Times New Roman', 16),
                fg="white",
                bg="#26242f")

Button0 = Button(root, height=1,
                 width=13,
                 text="start",
                 command=lambda: Take_input(),
                 font=('Times New Roman', 17),
                 fg="white",
                 bg="#26242f")

Output = Label(text="",
               fg="white",
               bg="#26242f")

l.pack(padx=4, pady=4)
inputtxt.bind('<Return>', lambda _: Take_input())
inputtxt.pack(padx=4, pady=4)
Button0.pack(padx=5, pady=5)
Output.pack(padx=4, pady=4)

# Thread definition
receive_thread = threading.Thread(target=pinger)

mainloop()
